name: flutter_login
description: "Pacote Flutter para a funcionalidade de login"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true